USE master;
GO

IF DB_ID('RankForge') IS NOT NULL
BEGIN
    ALTER DATABASE RankForge SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE RankForge;
END;
GO

CREATE DATABASE RankForge;
GO

USE RankForge;
GO